### ISSUE TITLE
[Enhancement] Cygwin support

### ISSUE THREAD

**Issue by RevoSucks** [pret/agbcc#2]
This feature is a must if we're (TPP Devs) to work with Gen 3.

**Comment by ghost** [comment]
What would this entail? If you install devkitARM using the Windows installer, it should work with cygwin already. I didn't experience any problems when I installed cygwin and compiled this project using the cygwin gcc. Have you had issues with this project using cygwin?

Also, the pokeruby project associated with this compiler still needs a lot of work before the ROM can be edited. Currently any deviations from the original ROM will result in problems due to pointers in the data that have not yet been found. Only the pointers in the code have all been found.

**Comment by RevoSucks** [comment]
It appears this issue was a result of https://github.com/YamaArashi/agbcc/issues/1 . Please merge.
